### PR TITLE
make myself actually happy

### PR DESCRIPTION
**Pull request by JOPHESTUS**

### CODE REVIEW

**Comment by DSH105** [comment]
How is this in compliance with the output of other commands? :(

**Comment by stuntguy3000** [comment]
How hypocritical of yourself @DSH105 when you violate proper API usage. >:0

**Comment by DSH105** [comment]
@stuntguy3000 I try my best :'(

**Comment by JOPHESTUS** [comment]
@DSH105 wut

**Comment by JOPHESTUS** [comment]
<Nexus> (JOPHESTUS) Use \help remind for help (Schedule a reminder).

like that

**Comment by DSH105** [comment]
Which implies that the receiver of the command sent it.

**Comment by JOPHESTUS** [comment]
@DSH105 comon. The current state of affairs is a mess.

**Comment by lol768** [comment]
PR cannot be merged, closing...

**Comment by DSH105** [comment]
You are a bad person, @lol768

**Comment by JOPHESTUS** [comment]
:clap: :clap: nice one @lol768

**Comment by JOPHESTUS** [comment]
You are a horrible excuse for a person @lol768

**Pull request closed without merging**
