### PR TITLE
added weather forecast command

### PR DESCRIPTION
**Pull request by JOPHESTUS**
I think I remembered everything

### CODE REVIEW

**Comment by DSH105** [comment]
:D

**Comment by JOPHESTUS** [comment]
nope. Forgot to add the updated readme

**Comment by lol768** [comment]
@JOPHESTUS Can we get kToC unit tested?

@DSH105 Thoughts about moving all the xToX functions into a TemperatureUtil class?

**Comment by DSH105** [comment]
@lol768 Would be a nice way to keep everything together ;D

**Pull request merged**
