### PR TITLE
Add option to disable command

### PR DESCRIPTION
**Pull request by stuntguy3000**
Now, this PR stems from the recent \insult incident. For much bigger commands, it would be nice for a way to disable them, rather then delete the class (and the code). One example would be for a service that needs to be improved. e.g. weather, say it breaks and a resolution cannot be found quickly. This would be a good(enough) solution.

### CODE REVIEW

**Comment by lol768** [comment]
This would ideally be per channel.

**Comment by stuntguy3000** [comment]
Infrastructure is not available for that kind of feature, yet.

**Comment by lol768** [comment]
Perfect time to add it :smile:

**Comment by DSH105** [comment]
As I mentioned in IRC (and as @lol768 stated above), this should be per-channel (global disabling included).

A hard-coded switch is not really a solution to this :P

**Pull request closed without merging**
