### PR TITLE
JavaDoc some Util methods and organize exceptions

### PR DESCRIPTION
**Pull request by stuntguy3000**
**The Issue**
Exception classes should be organised.

**Justification for this PR:**
To maintain proper, organized code.

**Breakdown**
- Organize exceptions following hook template
- JavaDoc a range of Util Methods _(Looked for an excuse to practise 'JavaDoc' generation)_
- _(Automatically done by Intellij)_ Removed some unused imports

### CODE REVIEW

**Comment by lol768** [comment]
Per http://stackoverflow.com/questions/2236807/java-naming-convention-with-acronyms

> For 4+ letter acronyms, use mixed case. The standard library does this, and it just makes good sense. 

Looks good otherwise.

**Comment by stuntguy3000** [comment]
I see (but disagree).

**Comment by DSH105** [comment]
I prefer **JsonUtil** over **JSONUtil** :)

**Comment by DSH105** [comment]
And please follow the PR formatting guides. When you've fixed those two things I'll merge it :)

**Comment by stuntguy3000** [comment]
@DSH105 Done.

**Comment by DSH105** [comment]
Sorry about messing up with git <3

**Pull request merged**
