### PR TITLE
Add support for pi

### PR DESCRIPTION
**Pull request by blha303**

### CODE REVIEW

**Comment by DSH105** [comment]
wat

**Comment by JOPHESTUS** [comment]
@lol768 :clap:

**Comment by lol768** [comment]
wut

**Comment by JOPHESTUS** [comment]
@lol768 :clap:

**Comment by blha303** [comment]
@JOPHESTUS :clapper:

**Comment by DSH105** [comment]
@lol768 :clap:

**Comment by lol768** [comment]
I'm sorry :(

**Comment by blha303** [comment]
Fiiiiiiiiiiiine

**Pull request closed without merging**
