### PR TITLE
Add Minecraft Commands

### PR DESCRIPTION
**Pull request by stuntguy3000**
The following Pull request adds two commands to help improve the user experience as well as improve functionality of Nexus. The two commands are "mcuser" and "mcping". These commands add two useful features to any IRC bot which is surrounded by Minecraft players.

"mcuser" is a command dedicated to providing a specific username's information, giving information such as UUID, validity and if it is a paid legitimate account. This command sends three HTTP Posts requests to three of Mojang's web based APIs to gather the required data as well as bringing "JSON-Simple" and "UUIDFetcher" classes into Nexus.

"mcping" is a command which allows a user to ping a specified hostname on any specific port. This cannot be used for more than Minecraft servers because it attempts to fetch more data from the successful ping. This returns specific server information, which includes the server's Message Of The Day, online player count, online players and maximum player count.

This Pull Request also includes minor internal re-arrangements for organizational purposes.

### CODE REVIEW

**Comment by lol768** [comment]
:heart: the description

**Comment by lol768** [comment]
Please rewrite necessary code to use existing JSON lib

**Comment by DSH105** [comment]
!agree

**Comment by stuntguy3000** [comment]
Also agree, just too lazy to do it.

_mumbles while walking away and does it_

**Comment by stuntguy3000** [comment]
@DSH105 Rewrote to use existing lib :)

**Pull request merged**
